# Advanced Parkour Environment Configuration
environment:
  name: "advanced_parkour"
  description: "Comprehensive parkour environment with dynamic obstacles and curriculum learning"
  
# Simulation settings
simulation:
  dt: 0.005  # Physics timestep
  substeps: 1
  gravity: [0.0, 0.0, -9.81]
  
# Terrain settings
terrain:
  type: "procedural"  # procedural, heightfield, mesh, mixed
  size: [200.0, 200.0]  # [x, y] meters
  resolution: 0.05  # meters per pixel
  border_size: 10.0  # meters of flat border around terrain
  
  # Procedural terrain parameters
  procedural:
    slope_threshold: 0.75
    height_noise_scale: 0.1
    height_range: [-0.5, 1.5]  # meters
    
    # Obstacle types and their configurations
    obstacles:
      stairs:
        probability: 0.15
        height_range: [0.05, 0.4]  # meters
        width_range: [0.3, 1.5]    # meters
        depth_range: [0.2, 0.8]    # meters
        step_height: [0.05, 0.15]  # meters per step
        
      gaps:
        probability: 0.08
        width_range: [0.2, 1.2]    # meters
        depth_range: [0.1, 0.8]    # meters
        bridge_probability: 0.3    # chance of narrow bridge
        
      slopes:
        probability: 0.25
        angle_range: [0.1, 0.6]    # radians (6-34 degrees)
        length_range: [1.0, 4.0]   # meters
        
      rough_terrain:
        probability: 0.3
        roughness_scale: [0.05, 0.2]  # meters
        frequency: [1.0, 5.0]         # spatial frequency
        
      platforms:
        probability: 0.1
        height_range: [0.1, 0.6]   # meters
        size_range: [0.5, 2.0]     # meters
        
      narrow_beam:
        probability: 0.05
        width_range: [0.1, 0.3]    # meters
        height_range: [0.1, 0.4]   # meters
        length_range: [1.0, 3.0]   # meters
        
      stepping_stones:
        probability: 0.07
        stone_size: [0.2, 0.5]     # meters
        spacing: [0.3, 0.8]        # meters
        height_variation: [0.0, 0.3]  # meters

# Environmental conditions
conditions:
  # Lighting variations
  lighting:
    sun_intensity: [0.7, 1.3]
    ambient_intensity: [0.2, 0.5]
    shadow_quality: "medium"
    
  # Weather effects (if enabled)
  weather:
    enabled: false
    wind_strength: [0.0, 5.0]  # m/s
    rain_intensity: [0.0, 0.3]  # 0-1 scale
    
  # Surface properties
  surface:
    friction_coefficient: [0.8, 1.2]
    restitution: [0.0, 0.3]
    damping: [0.1, 0.5]

# Episode settings
episode:
  max_episode_length: 1500  # steps
  timeout_penalty: -100.0
  success_reward: 500.0
  
  # Success criteria
  success_conditions:
    min_distance: 20.0  # meters forward progress
    max_time: 1500      # steps
    
  # Reset conditions
  reset_conditions:
    base_contact: true
    base_height_threshold: 0.08  # meters
    roll_pitch_threshold: 1.57   # radians
    out_of_bounds: true
    
# Curriculum learning
curriculum:
  enabled: true
  
  # Terrain difficulty progression
  terrain_difficulty:
    initial: 0.0
    final: 1.0
    increment_threshold: 0.75  # success rate threshold
    increment_step: 0.05
    decrement_threshold: 0.3   # failure rate threshold
    decrement_step: 0.02
    
  # Command velocity progression
  command_velocity:
    linear:
      initial: [0.5, 0.0, 0.0]  # [vx, vy, vz]
      final: [3.0, 1.0, 0.0]
      increment_threshold: 0.8
      increment_step: 0.1
    angular:
      initial: [0.0, 0.0, 0.2]  # [wx, wy, wz]
      final: [0.0, 0.0, 1.5]
      increment_threshold: 0.8
      increment_step: 0.1
      
  # Obstacle complexity progression
  obstacle_complexity:
    initial_types: ["rough_terrain", "slopes"]
    intermediate_types: ["stairs", "platforms", "gaps"]
    advanced_types: ["narrow_beam", "stepping_stones"]
    
# Observation space
observations:
  # Proprioceptive observations (robot state)
  proprioceptive:
    base_linear_velocity: true    # 3D
    base_angular_velocity: true   # 3D
    base_orientation: true        # 3D (gravity vector)
    joint_positions: true         # nDoF
    joint_velocities: true        # nDoF
    actions: true                 # nDoF (previous actions)
    
  # Exteroceptive observations (environment)
  exteroceptive:
    height_measurements: true
    height_scan_points: 256       # number of points in height scan
    height_scan_range: 4.0        # meters
    terrain_normal: true          # 3D surface normal under robot
    
  # Privileged information (not available during deployment)
  privileged:
    terrain_type: true            # current terrain type
    friction_coefficient: true    # surface friction
    obstacle_positions: true      # nearby obstacle positions
    
  # Historical observations
  history:
    enabled: true
    length: 15                    # number of time steps
    subsample: 2                  # keep every nth observation
    
# Action space
actions:
  type: "joint_positions"  # joint_positions, joint_velocities, joint_torques
  dimension: 12             # number of actuated joints
  clip_range: [-1.0, 1.0]  # action clipping
  
# Randomization (Domain Randomization)
randomization:
  enabled: true
  
  # Physics randomization
  physics:
    mass:
      enabled: true
      range: [0.7, 1.3]  # multiplier
    center_of_mass:
      enabled: true
      range: [-0.05, 0.05]  # meters offset
    inertia:
      enabled: true
      range: [0.8, 1.2]  # multiplier
    friction:
      enabled: true
      range: [0.4, 1.8]  # coefficient
    restitution:
      enabled: true
      range: [0.0, 0.6]
    joint_properties:
      stiffness_range: [0.7, 1.3]
      damping_range: [0.5, 1.5]
      
  # External disturbances
  external_forces:
    enabled: true
    force_range: [-150.0, 150.0]  # Newtons per axis
    torque_range: [-50.0, 50.0]   # Newton-meters per axis
    application_probability: 0.1  # per step
    duration_range: [0.1, 0.5]    # seconds
    
  # Sensor noise
  noise:
    observations:
      enabled: true
      base_velocity_std: 0.05
      joint_position_std: 0.01
      joint_velocity_std: 0.1
      height_scan_std: 0.02
    actions:
      enabled: true
      std: 0.02
      
  # Visual variations
  visual:
    enabled: false  # Enable for vision-based training
    lighting_range: [0.5, 1.5]
    texture_randomization: true
    color_randomization: true
    
# Rewards
rewards:
  # Tracking rewards
  forward_velocity: 2.0
  lateral_velocity: -0.1
  angular_velocity_z: 0.8
  
  # Efficiency rewards
  energy_consumption: -2e-6
  action_smoothness: -0.02
  
  # Stability rewards
  orientation_penalty: -8.0
  height_penalty: -15.0
  velocity_z_penalty: -3.0
  angular_velocity_xy_penalty: -0.1
  
  # Gait rewards
  foot_contact_reward: 1.5
  foot_clearance_reward: 0.8
  symmetric_gait: 0.5
  
  # Parkour specific
  obstacle_clearing: 10.0
  landing_stability: 5.0
  progression_bonus: 1.0
  exploration_bonus: 0.2
  
  # Penalties
  collision_penalty: -10.0
  stumble_penalty: -5.0
  joint_limit_penalty: -20.0
  
# Logging and visualization
logging:
  log_interval: 50  # episodes
  video_recording: true
  video_interval: 100  # episodes
  metrics_to_log:
    - "success_rate"
    - "episode_length"
    - "forward_distance"
    - "energy_efficiency"
    - "stability_score"
