# Unitree A1 Robot Configuration
robot:
  name: "unitree_a1"
  urdf_path: "resources/robots/unitree_a1/unitree_a1.urdf"
  
# Physical properties
physics:
  mass: 12.0  # kg
  height: 0.35  # m
  inertia: [0.033, 0.0, 0.0, 0.0, 0.42, 0.0, 0.0, 0.0, 0.458]  # [Ixx, Ixy, Ixz, Iyx, Iyy, Iyz, Izx, Izy, Izz]
  
# Initial state
init_state:
  position: [0.0, 0.0, 0.35]  # x, y, z [m]
  orientation: [0.0, 0.0, 0.0, 1.0]  # quaternion [x, y, z, w]
  linear_velocity: [0.0, 0.0, 0.0]  # [m/s]
  angular_velocity: [0.0, 0.0, 0.0]  # [rad/s]
  
  # Joint angles [rad] - specific to A1 robot
  joint_angles:
    FL_hip_joint: 0.1
    RL_hip_joint: 0.1
    FR_hip_joint: -0.1
    RR_hip_joint: -0.1
    FL_thigh_joint: 0.8
    RL_thigh_joint: 1.0
    FR_thigh_joint: 0.8
    RR_thigh_joint: 1.0
    FL_calf_joint: -1.5
    RL_calf_joint: -1.5
    FR_calf_joint: -1.5
    RR_calf_joint: -1.5

# Control settings
control:
  type: "position"  # position, velocity, torque
  decimation: 4  # Control frequency = sim_frequency / decimation
  action_scale: 0.25
  
  # PD gains - tuned for A1
  stiffness:
    hip: 20.0
    thigh: 20.0
    calf: 20.0
  damping:
    hip: 0.5
    thigh: 0.5
    calf: 0.5
    
  # Joint limits [rad] - A1 specific
  joint_limits:
    hip: [-0.802, 0.802]  # ±46 degrees
    thigh: [-1.047, 4.538]  # -60 to 260 degrees
    calf: [-2.696, -0.916]  # -154.5 to -52.5 degrees

# Sensor configuration
sensors:
  imu:
    enabled: true
    noise_std: 0.01
    update_rate: 400  # Hz
  joint_encoders:
    enabled: true
    noise_std: 0.001
    update_rate: 1000  # Hz
  contact_sensors:
    enabled: true
    bodies: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]
    threshold: 1.0  # N
  height_scanner:
    enabled: true
    num_points: 187
    range: 3.0  # meters
    resolution: 0.1  # meters
    
# Asset settings
asset:
  file: "resources/robots/unitree_a1/unitree_a1.urdf"
  foot_name: "foot"
  penalize_contacts_on: ["thigh", "calf"]
  terminate_after_contacts_on: ["base", "thigh"]
  self_collisions: false
  fix_base_link: false
  
# Reward configuration - tuned for parkour
rewards:
  # Primary tracking rewards
  linear_velocity_xy: 1.0
  angular_velocity_z: 0.5
  
  # Regularization rewards
  joint_acceleration: -2.5e-7
  action_rate: -0.01
  torques: -1e-5
  dof_vel: -1e-4
  dof_acc: -2.5e-7
  
  # Stability rewards
  orientation: -5.0
  base_height: -10.0
  lin_vel_z: -2.0
  ang_vel_xy: -0.05
  
  # Gait rewards
  feet_air_time: 1.0
  collision: -5.0
  stumble: -2.0
  stand_still: -0.1
  
  # Parkour specific rewards
  forward_progress: 2.0
  energy_efficiency: -1e-6
  foot_clearance: 0.5
  landing_impact: -0.1
  
# Termination conditions
termination:
  base_contact: true
  base_height_threshold: 0.15  # meters
  roll_pitch_threshold: 1.57  # radians (90 degrees)
  joint_limit_violation: true
  
# Randomization for robustness
randomization:
  # Mass randomization
  mass_range: [0.8, 1.2]  # multiplier
  
  # Friction randomization
  friction_range: [0.5, 1.25]
  
  # External forces
  push_force_range: [-200, 200]  # N
  push_interval: [0.5, 3.0]  # seconds
  
  # Joint properties
  joint_stiffness_range: [0.8, 1.2]
  joint_damping_range: [0.8, 1.2]
  
  # Sensor noise
  imu_noise_scale: [0.5, 2.0]
  joint_encoder_noise_scale: [0.5, 2.0]
